### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by fabianegli** [qbicsoftware/metadata-utils-lib#2]
I am looking into openBIS and it's ecosystem to asses it's use for our lab and found your project by searching github for openbis. It looks really nice, but it is not clear to me what use cases arrive from this piece of programming. A bunch of example use cases and some text in the README.md explaining them would help me, and probably anyone else passing by, to understand what we can do with this.

**Comment by jenniferboedker** [comment]
Hello Fabian,

thanks for your interest in this project. This is an old repository though and was reworked here https://github.com/qbicsoftware/metastats-cli/tree/development. 
You can find documentation in this repository and descriptions on how to run it. If you have further questions you can also contact me directly via jennifer.boedker@qbic.uni-tuebingen.de

Best
Jennifer
